###模拟演示死信队列
zcm:
  dlx:
    exchange: zcm_dlx_exchange
    queue: zcm_order_dlx_queue
    routingKey: dlx
  ###备胎交换机
  order:
    exchange: zcm_order_exchange
    queue: zcm_order_queue
    routingKey: zcm.order